import { listMediaAssets } from "@/lib/cms/admin-queries";

import { saveMedia } from "./actions";

const input = "rounded-xl border border-white/15 bg-black/25 px-3 py-2.5";

function MediaForm({ media }: { media?: Awaited<ReturnType<typeof listMediaAssets>>[number] }) {
  return <form action={saveMedia.bind(null, media?.id ?? null)} className="grid gap-3 md:grid-cols-2"><select className={input} defaultValue={media?.mediaType ?? 'IMAGE'} name="mediaType">{['IMAGE','VIDEO','AUDIO','DOCUMENT'].map((value) => <option key={value}>{value}</option>)}</select><input className={input} defaultValue={media?.url ?? ''} name="url" placeholder="Approved asset URL" required type="url" /><input className={input} defaultValue={media?.altText ?? ''} name="altText" placeholder="Descriptive alt text" /><input className={input} defaultValue={media?.credit ?? ''} name="credit" placeholder="Credit" /><input className={input} defaultValue={media?.width ?? ''} min="1" name="width" placeholder="Width" type="number" /><input className={input} defaultValue={media?.height ?? ''} min="1" name="height" placeholder="Height" type="number" /><input className={input} defaultValue={media?.mimeType ?? ''} name="mimeType" placeholder="image/webp" /><input className={input} defaultValue={media?.focalPoint ?? ''} name="focalPoint" placeholder="50% 50%" /><textarea className={input} defaultValue={media?.caption ?? ''} name="caption" placeholder="Caption" /><textarea className={input} defaultValue={media?.licenseNotes ?? ''} name="licenseNotes" placeholder="Source and license notes" /><input className={`${input} md:col-span-2`} defaultValue={media?.sourceUrl ?? ''} name="sourceUrl" placeholder="Original source URL" type="url" /><button className="min-h-11 rounded-full bg-cyan-300 px-5 font-black text-slate-950 md:col-span-2">{media ? 'Save asset' : 'Add asset record'}</button></form>;
}

export default async function MediaPage() { const rows = await listMediaAssets(); return <div><p className="text-xs font-black uppercase tracking-[0.24em] text-cyan-300">Editorial assets</p><h1 className="mt-2 text-4xl font-black">Media library</h1><p className="mt-3 text-slate-300">This stores references and rights metadata. It does not scrape or download third-party material.</p><section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.035] p-6"><h2 className="mb-5 text-xl font-black">Add approved asset</h2><MediaForm /></section><div className="mt-8 space-y-4">{rows.map((media) => <details className="rounded-2xl border border-white/10 p-5" key={media.id}><summary className="cursor-pointer font-black">{media.altText ?? media.url} <span className="ml-2 text-sm font-normal text-slate-400">{media.mediaType} · {media.width ?? '?'}×{media.height ?? '?'}</span></summary><div className="mt-5"><MediaForm media={media} /></div></details>)}</div></div>; }
