import Link from "next/link";
import { notFound } from "next/navigation";

import { ScorePill } from "@/components/admin/score-pill";
import { requireEditor } from "@/lib/auth/dal";
import { canManageDiscovery, canVerifyDiscovery } from "@/lib/auth/discovery-permissions";
import { getDiscoveryCandidate } from "@/lib/discovery/admin-queries";
import { leakSafetyNotice } from "@/lib/discovery/safety";

import { addCandidateEvidence, mergeCandidateIntoCluster, promoteCandidateToDraft, rejectCandidate, startCandidateResearch, updateCandidateVerification } from "../actions";

const fieldClass = "mt-2 w-full rounded-xl border border-white/15 bg-black/25 px-4 py-3 text-white outline-none focus:border-cyan-300";

export default async function DiscoveryCandidatePage({ params }: { params: Promise<{ id: string }> }) {
  const editor = await requireEditor();
  const { id } = await params;
  const record = await getDiscoveryCandidate(id, editor);
  if (!record) notFound();
  const { candidate, source, cluster } = record;
  const canManage = canManageDiscovery(editor.role);
  const canReview = canVerifyDiscovery(editor.role);

  return (
    <div>
      <p className="text-xs font-black uppercase tracking-[0.24em] text-cyan-300">{candidate.status.replaceAll("_", " ")} · {source.authorityTier.replace("_", " ")}</p>
      <h1 className="mt-2 max-w-5xl text-4xl font-black tracking-tight">{candidate.title}</h1>
      <p className="mt-3 max-w-4xl text-slate-300">{candidate.excerpt ?? "INSUFFICIENT EVIDENCE — open the original source and document supported facts before drafting."}</p>
      <div className="mt-5 flex flex-wrap gap-2"><ScorePill label="News" score={candidate.newsworthinessScore} /><ScorePill label="Confidence" score={candidate.confidenceScore} /><ScorePill label="SEO" score={candidate.seoOpportunityScore} /><ScorePill label="Trend" score={candidate.trendScore} /><ScorePill label="Quick Hit" score={candidate.quickHitScore} /><ScorePill label="Video" score={candidate.primaryVideoScore} /></div>

      <div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
        <div className="space-y-6">
          <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><h2 className="text-xl font-black">Evidence and verification</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-black uppercase tracking-wider text-slate-500">Recommendation</dt><dd className="mt-1 font-bold">{candidate.verificationRecommendation.replaceAll("_", " ")}</dd></div><div><dt className="text-xs font-black uppercase tracking-wider text-slate-500">Primary source</dt><dd className="mt-1 font-bold">{source.name}</dd></div><div><dt className="text-xs font-black uppercase tracking-wider text-slate-500">Source authority</dt><dd className="mt-1">{source.authorityTier.replace("_", " ")} · {source.reliabilityScore}/100</dd></div><div><dt className="text-xs font-black uppercase tracking-wider text-slate-500">Duplicate status</dt><dd className="mt-1">{candidate.duplicateStatus.replaceAll("_", " ")}</dd></div></dl><a className="mt-5 inline-flex min-h-11 items-center rounded-full border border-cyan-300/40 px-5 font-bold text-cyan-200" href={candidate.sourceUrl} rel="noreferrer" target="_blank">Open original source</a>{candidate.verificationRecommendation === "ALLEGED_LEAK" ? <p className="mt-5 rounded-2xl border border-rose-300/30 bg-rose-300/[0.05] p-4 text-sm leading-6 text-rose-100">{leakSafetyNotice}</p> : null}</section>
          <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><h2 className="text-xl font-black">Known facts</h2>{candidate.knownFacts.length ? <ul className="mt-4 space-y-3">{(candidate.knownFacts as Array<{ fact: string; sourceUrl: string }>).map((fact, index) => <li className="rounded-xl border border-white/10 p-4" key={`${fact.sourceUrl}-${index}`}><p>{fact.fact}</p><a className="mt-2 block break-all text-xs text-cyan-300" href={fact.sourceUrl} rel="noreferrer" target="_blank">{fact.sourceUrl}</a></li>)}</ul> : <p className="mt-4 text-amber-200">INSUFFICIENT EVIDENCE</p>}<h3 className="mt-7 font-black">Uncertainties</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-300">{candidate.uncertainties.map((uncertainty) => <li key={uncertainty}>{uncertainty}</li>)}</ul>{candidate.communityQuestions.length ? <><h3 className="mt-7 font-black">Repeated community questions</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-300">{candidate.communityQuestions.map((question) => <li key={question}>{question}</li>)}</ul></> : null}</section>
          <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><h2 className="text-xl font-black">Evidence records</h2>{record.evidence.length ? <ol className="mt-4 space-y-3">{record.evidence.map((evidence) => <li className="rounded-xl border border-white/10 p-4" key={evidence.id}><p className="font-bold">{evidence.title}</p><p className="mt-1 text-xs text-slate-500">{evidence.authorityTier.replace("_", " ")} · {evidence.authorityScore}/100{evidence.isPrimary ? " · Primary" : " · Corroborating"}</p><a className="mt-2 block break-all text-xs text-cyan-300" href={evidence.sourceUrl} rel="noreferrer" target="_blank">{evidence.sourceUrl}</a></li>)}</ol> : <p className="mt-3 text-sm text-slate-400">No supporting evidence has been recorded.</p>}</section>
          <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><h2 className="text-xl font-black">Editorial opportunities</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="font-black">Search intent</h3><p className="mt-2 text-sm leading-6 text-slate-300">{candidate.searchIntent ?? "Not yet classified."}</p></div><div><h3 className="font-black">Evergreen update</h3><p className="mt-2 text-sm leading-6 text-slate-300">{candidate.evergreenUpdateRecommended ? candidate.evergreenRecommendation ?? "Recommended" : "No update recommended yet."}</p></div><div><h3 className="font-black">13-second angle</h3><p className="mt-2 text-sm leading-6 text-slate-300">{candidate.quickHitAngle ?? "Not yet suggested."}</p></div><div><h3 className="font-black">61–90 second angle</h3><p className="mt-2 text-sm leading-6 text-slate-300">{candidate.primaryVideoAngle ?? "Not yet suggested."}</p></div></div>{candidate.storyAngles.length ? <ul className="mt-5 list-disc space-y-2 pl-5 text-slate-300">{candidate.storyAngles.map((angle) => <li key={angle}>{angle}</li>)}</ul> : null}</section>
          {cluster ? <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Story cluster</h2><Link className="font-bold text-cyan-300" href={`/admin/discovery/clusters/${cluster.id}`}>Open cluster</Link></div><p className="mt-3 font-bold">{cluster.title}</p><ol className="mt-4 space-y-3">{record.clusterCandidates.map((related) => <li className="rounded-xl border border-white/10 p-4" key={related.id}><Link className="font-bold hover:text-cyan-300" href={`/admin/discovery/${related.id}`}>{related.title}</Link><p className="mt-1 text-xs text-slate-500">{related.sourceTier.replace("_", " ")} · {related.sourceName} · {related.status.replaceAll("_", " ")}</p></li>)}</ol></section> : null}
        </div>

        <aside className="space-y-6">
          {canManage ? <section className="rounded-3xl border border-cyan-300/20 bg-cyan-300/[0.035] p-5"><h2 className="text-lg font-black">Editorial actions</h2><form action={startCandidateResearch} className="mt-4"><input name="candidateId" type="hidden" value={candidate.id} /><button className="min-h-11 w-full rounded-full border border-cyan-300/40 font-bold text-cyan-100">Research</button></form><form action={promoteCandidateToDraft} className="mt-3"><input name="candidateId" type="hidden" value={candidate.id} /><button className="min-h-11 w-full rounded-full bg-cyan-300 font-black text-slate-950">Promote to private draft</button></form><p className="mt-3 text-xs leading-5 text-slate-400">Promotion creates a DRAFTING story only. It cannot approve, schedule, or publish.</p><form action={rejectCandidate} className="mt-5"><input name="candidateId" type="hidden" value={candidate.id} /><label className="text-sm font-bold">Rejection reason<textarea className={`${fieldClass} min-h-24`} name="reason" required /></label><button className="mt-3 min-h-11 w-full rounded-full border border-rose-300/40 font-bold text-rose-100">Reject</button></form></section> : null}
          <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-black">Add supporting evidence</h2><p className="mt-2 text-xs leading-5 text-slate-400">Store source metadata and supported facts only. No media is downloaded.</p><form action={addCandidateEvidence} className="mt-4 space-y-4"><input name="candidateId" type="hidden" value={candidate.id} /><label className="block text-sm font-bold">Registered source<select className={fieldClass} name="sourceId" required>{record.availableSources.map((available) => <option key={available.id} value={available.id}>{available.authorityTier.replace("_", " ")} · {available.name}</option>)}</select></label><label className="block text-sm font-bold">Evidence URL<input className={fieldClass} name="sourceUrl" placeholder="https://" required type="url" /></label><label className="block text-sm font-bold">Title<input className={fieldClass} name="title" required /></label><label className="block text-sm font-bold">Author<input className={fieldClass} name="author" /></label><label className="block text-sm font-bold">Published at<input className={fieldClass} name="publishedAt" type="datetime-local" /></label><label className="block text-sm font-bold">Supported facts, one per line<textarea className={`${fieldClass} min-h-28`} name="extractedFacts" required /></label><label className="block text-sm font-bold">Verification notes<textarea className={`${fieldClass} min-h-24`} name="verificationNotes" /></label><button className="min-h-11 w-full rounded-full border border-cyan-300/40 font-bold text-cyan-100">Add evidence</button></form></section>
          {canReview ? <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-black">Fact-check review</h2><form action={updateCandidateVerification} className="mt-4 space-y-4"><input name="candidateId" type="hidden" value={candidate.id} /><label className="block text-sm font-bold">Verification<select className={fieldClass} defaultValue={candidate.verificationRecommendation} name="verificationRecommendation">{["CONFIRMED", "CREDIBLE_REPORT", "RUMOR", "SPECULATION", "ALLEGED_LEAK"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="block text-sm font-bold">Confidence<input className={fieldClass} defaultValue={candidate.confidenceScore} max={100} min={0} name="confidenceScore" type="number" /></label><label className="block text-sm font-bold">Research notes<textarea className={`${fieldClass} min-h-32`} defaultValue={candidate.researchNotes ?? ""} name="researchNotes" /></label><label className="block text-sm font-bold">Uncertainties, one per line<textarea className={`${fieldClass} min-h-32`} defaultValue={candidate.uncertainties.join("\n")} name="uncertainties" /></label><label className="block text-sm font-bold">Repeated community questions, one per line<textarea className={`${fieldClass} min-h-28`} defaultValue={candidate.communityQuestions.join("\n")} name="communityQuestions" /></label><button className="min-h-11 w-full rounded-full border border-amber-300/40 font-bold text-amber-100">Save verification review</button></form></section> : null}
          {canManage ? <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-black">Merge into cluster</h2><form action={mergeCandidateIntoCluster} className="mt-4"><input name="candidateId" type="hidden" value={candidate.id} /><label className="text-sm font-bold">Cluster ID<input className={fieldClass} name="clusterId" required /></label><button className="mt-3 min-h-11 w-full rounded-full border border-white/15 font-bold">Merge</button></form></section> : null}
          <section className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-black">Audit trail</h2>{record.audit.length ? <ol className="mt-4 space-y-3">{record.audit.map((entry) => <li className="border-l border-white/15 pl-3 text-sm" key={entry.id}><p className="font-bold">{entry.action.replaceAll("_", " ")}</p><p className="text-slate-400">{entry.reason}</p><time className="text-xs text-slate-500">{entry.createdAt.toLocaleString("en-US")}</time></li>)}</ol> : <p className="mt-3 text-sm text-slate-400">No actions recorded yet.</p>}</section>
        </aside>
      </div>
    </div>
  );
}
