import { listMediaAssets, listVideos } from "@/lib/cms/admin-queries";

import { saveVideo } from "./actions";

const input = "rounded-xl border border-white/15 bg-black/25 px-3 py-2.5";

function VideoForm({ video, media }: { video?: Awaited<ReturnType<typeof listVideos>>[number]['video']; media: Awaited<ReturnType<typeof listMediaAssets>> }) {
  return <form action={saveVideo.bind(null, video?.id ?? null)} className="grid gap-3 md:grid-cols-2"><select className={input} defaultValue={video?.kind ?? 'PRIMARY'} name="kind">{['PRIMARY','QUICK_HIT','TRAILER','CLIP'].map((value) => <option key={value}>{value}</option>)}</select><input className={input} defaultValue={video?.title ?? ''} name="title" placeholder="Video title" required /><textarea className={`${input} md:col-span-2`} defaultValue={video?.description ?? ''} name="description" placeholder="Description" /><select className={input} defaultValue={video?.thumbnailMediaId ?? ''} name="thumbnailMediaId"><option value="">No approved thumbnail</option>{media.filter((asset) => asset.mediaType === 'IMAGE').map((asset) => <option key={asset.id} value={asset.id}>{asset.altText ?? asset.url}</option>)}</select><input className={input} defaultValue={video?.durationSeconds ?? ''} min="1" name="durationSeconds" placeholder="Duration in seconds; Quick Hits = 13" type="number" /><input className={input} defaultValue={video?.platform ?? ''} name="platform" placeholder="Platform" /><input className={input} defaultValue={video?.contentUrl ?? ''} name="contentUrl" placeholder="Content URL" type="url" /><input className={input} defaultValue={video?.embedUrl ?? ''} name="embedUrl" placeholder="Embed URL" type="url" /><input className={input} defaultValue={video?.captionsUrl ?? ''} name="captionsUrl" placeholder="Captions URL" type="url" /><textarea className={`${input} min-h-32 md:col-span-2`} defaultValue={video?.transcript ?? ''} name="transcript" placeholder="Transcript" />{(['tiktokUrl','youtubeUrl','instagramUrl','facebookUrl'] as const).map((name) => <input className={input} defaultValue={video?.[name] ?? ''} key={name} name={name} placeholder={name} type="url" />)}<label><input defaultChecked={video?.isPublished ?? false} name="isPublished" type="checkbox" /> Approved and published asset</label><button className="min-h-11 rounded-full bg-cyan-300 px-5 font-black text-slate-950">{video ? 'Save video' : 'Add video record'}</button></form>;
}

export default async function VideosPage() { const rows = await listVideos(); const media = await listMediaAssets(); return <div><p className="text-xs font-black uppercase tracking-[0.24em] text-cyan-300">Future distribution architecture</p><h1 className="mt-2 text-4xl font-black">Videos and Quick Hits</h1><p className="mt-3 text-slate-300">No posting API is active. Quick Hit records enforce the approved 13-second format and require real assets before publication.</p><section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.035] p-6"><h2 className="mb-5 text-xl font-black">Add video record</h2><VideoForm media={media} /></section><div className="mt-8 space-y-4">{rows.map(({ video }) => <details className="rounded-2xl border border-white/10 p-5" key={video.id}><summary className="cursor-pointer font-black">{video.title} <span className="ml-2 text-sm font-normal text-slate-400">{video.kind.replaceAll('_',' ')} · {video.isPublished ? 'Published asset' : 'Internal only'}</span></summary><div className="mt-5"><VideoForm media={media} video={video} /></div></details>)}</div></div>; }
